### ISSUE TITLE
Template Literals

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/platformscript#14]
Right now every string has a set of holes that can be plugged by a reference. Instead, we need the holes to be aribtrary platform script expressions:

```yaml
$let:
  say: "Hello"
  to: "world"
$do: "Hello, %({$capitalize: $to })"
```

A string with any number of `%()` expressions in it should parse not as a `PSString`, but as a `PSTemplate` that evaluates to a string.
