### ISSUE TITLE
binding expressions for function invocation

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/platformscript#15]
One of the nice things about PlatformScript function invocation syntax is that we get to have "extra" keys of the invocation. For example:

```yaml
$(x): "%($x.say), %({ $capitalize: $x.to })"
key1: ignored
key2: also ignored
```
We can use these keys as `$let` style binding expressions that enable you to compute subexpressions scoped to the function body.

```yaml
$(x): "%($say), %($to)"
say: $x.say
to: {$capitalize: $x.to}
```
