### ISSUE TITLE
improved module syntax

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/platformscript#57]
After working with PlatformScript for some more complex tasks, it is apparent that the module syntax and semantics are suboptimal.

## Import Syntax

Most modules have imports, but we currently have `2n+1` lines added to the source file where `n` is the number of imported modules. So importing from three modules will result in seven lines of preamble. We can do better, and cut in _half_ the number of lines dedicated to managing dependencies.

single named import:

```yaml
$import:
  suspend: https://pls.pub/std.yaml
```

multiple imports from the same package:

```yaml
$import:
  suspend, useContext: https://pls.pub/std.yaml
```

`*` import (all properties of a module bound to a value)

```yaml
$import:
  std<<: https://pls.pub/std.yaml
```

### before

```yaml
$import:
  - names: [suspend]
    from: https://pls.pub/std.yaml
  - names: [useBackstage]
    from: https://pls.pub/x/backstage.yaml
  - names: [GITHUB_TOKEN]
    from: ./secrets.yaml
```

### after

```yaml
$import:
  suspend: https://pls.pub/std.yaml
  useBackstage: https://pls.pub/x/backstage.yaml
  GITHUB_TOKEN: ./secrets.yaml
```

### Symbols

Right now the module has a list of "symbols" and a "value" which are two different things. So the following module:

```yaml
x: 1
y: 2
```
has symbols `x`, and `y`, i.e. things that can be imported into other modules, but its value is `false`. This is extremely counter intuitive, and to consume all the symbols as a single value is awkward and requires an accompanying `$do` statement which is how you define the "value" of a module. So to get "both" `x`, and `y`, you would have to define your module like this:

```yaml
x: 1
y: 2
$do: {x: $x, y: $y }
```
Otherwise it forces your consumers to do this work which is even worse;

```yaml
$import:
  x,y: https://pls.pub/x/mymod.yaml

together: {x: $x, y: $y}
```

Also, it is currently impossible to do something like transparently importing an entity defined with a function. Instead, you have to put it in a "pass through" property which is just a throw-away name. Consider defining a Backstage entity with a `defineEntity` function.

```yaml
$import:
  defineEntity: https://pls.pub/x/backstage@2.0.0/mod.yaml
entity:
  $defineEntity:
    kind: Component
    meta:
      name: artist-lookup
```

To consume this, you have to import the "entity" symbol from the module. 

```yaml
$import:
  entity: my-entity.yaml
```

The proposal then, is to just get ride of the "value" of a module, get rid of the `$do` syntax at the end of the module, and the value of the module is the value of the module, period. You can import a single symbol with the above import syntax, or get the entire value with the `<<name` binding. So the above becomes:

```yaml
$import:
  defineEntity: https://pls.pub/x/backstage@2.0.0/mod.yaml
$defineEntity:
  kind: Component
  meta:
    name: artist-lookup
```

That "merges" the entire entity onto the module definition.

### Potential Edge Cases

What do we do with a scalar module value? Like what about the the module defined as:

```yaml
# hello.yaml
Hello World
```

This clarifies that the "merge import" `name<<` is not really a "merge" in the sense of the `<<` native YAML merge key. Instead it is a "give me the whole module value"

```yaml
$import:
  message<<: ./hello.yaml
```

If this is defined as a module:

```yaml
$let:
  to: World
$do: Hello %($to)!
```
Then the value of the module should be `Hello World`

### Scoping

So that modules can define functions, the module's value *is* its own scope. So that keys which are already evaluated are in scope when subsequent keys are defined:

```yaml
to: World
msg: Hello %($to)!
```

should evaluate to:

```yaml
to: World
msg: Hello World!
```
that way, functions inside a module can call each other.

```yaml
greet(thing): Hello %($thing)
value: {$greet: World}
```

## Conclusions
  * modules do not have a set of symbols and a distinct value
  * imports can be named or all-inclusive, and can all be specified on a single line per-module
  * it is an error to make a named import on a module whose value is not a `map`
